export interface FormDataType {
  email: string
  userName: string
  password: string
  confirmpassword: string
  birthDate: string
  gender: string
  country: string
  firstName: string
  lastName: string
  userType: string
  year: string
  degree: string
  major: string
  department: string
  occupation: string
  universityId: string
  verificationEmail: string
  universityLogo: string
  verificationOtp: string
  universityEmail: string
  universityName: string
  UniversityOtp: string
  UniversityOtpOK: string
  referralCode?: string
  isJoinUniversity: boolean
  isUniversityVerified: boolean
  isEmailVerified: boolean
  universityDomain: string[]
}

export const value = [
  'Accounting',
  'Actuarial Science',
  'Advertising',
  'Aerospace Engineering',
  'African American Studies',
  'Agriculture',
  'Agronomy',
  'Anaesthesia',
  'Anatomy',
  'Animal Science',
  'Anthropology',
  'Applied Chemistry',
  'Applied Mathematics',
  'Applied Physics',
  'Architecture',
  'Area Studies',
  'Artificial Intelligence (AI)',
  'Arts',
  'Asian Studies',
  'Astronomy',
  'Astrophysics',
  'Australian Studies',
  'Banking',
  'Biochemistry',
  'Biological Engineering',
  'Biological Sciences',
  'Biology',
  'Biomedical Sciences',
  'Biotechnology',
  'Broadcast Journalism',
  'Buildings and Property Division',
  'Business',
  'Business Administration',
  'Business Law',
  'Business Statistics',
  'Career Development',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Clinical Health',
  'Clinical Psychology',
  'Clinical Sciences',
  'Cognitive Psychology',
  'Commercial Law',
  'Communication',
  'Comparative Literature',
  'Comparative Politics',
  'Computer Engineering',
  'Computer Science',
  'Computer Systems',
  'Corporate Communication',
  'Corporate Law',
  'Creative Writing',
  'Criminal Justice',
  'Criminology',
  'Culinary Arts',
  'Cultural Studies',
  'Curriculum Development',
  'Cybersecurity',
  'Dance',
  'Data Science',
  'Database Management',
  'Dentistry',
  'Design',
  'Developmental Biology',
  'Developmental Psychology',
  'Digital Marketing',
  'Disability Studies',
  'Disaster Management',
  'Diversity, Equity, and Inclusion',
  'Divinity',
  'Early Childhood Education',
  'Earth Science',
  'Econometrics',
  'Economics',
  'Ecotourism',
  'E-commerce',
  'Education',
  'Educational Leadership',
  'Educational Policy',
  'Electrical Engineering',
  'Electronics Engineering',
  'Employment',
  'Engineering',
  'English Language',
  'Entrepreneurship',
  'Environment',
  'Environmental Law',
  'Environmental Management',
  'Environmental Planning',
  'Environmental Science',
  'Epidemiology',
  'Equity',
  'Ethnic Studies',
  'Event Planning',
  'Executive Services',
  'External Relations',
  'Film Studies',
  'Finance',
  'Financial Planning',
  'Fine Arts',
  'Fisheries',
  'Forensic Medicine',
  'Forestry',
  'French',
  'Fundraising',
  'Gender Studies',
  'General Practice',
  'Geography',
  'Geology',
  'Geoscience',
  'Geospatial Information System (GIS)',
  'Global Business',
  'Graphic Design',
  'Gynaecology',
  'Health',
  'Health Information Management',
  'History',
  'Horticulture',
  'Hospitality',
  'Hotel Management',
  'Human Geography',
  'Human Resources',
  'Human Rights',
  'Humanities',
  'Immunology',
  'Indian Studies',
  'Indigenous Studies',
  'Information Systems',
  'Information Technology',
  'Interdisciplinary Studies',
  'Interior Architecture',
  'International Business',
  'International Law',
  'International Relations',
  'International Studies',
  'Investigative Journalism',
  'Investment Banking',
  'IT Project Management',
  'Japanese',
  'Journalism',
  'Justice Studies',
  'Landscape Architecture',
  'Languages',
  'Latin American Studies',
  'Law',
  'Legal Administration',
  'Legal Studies',
  'Libraries',
  'Library and Information Management',
  'Linguistics',
  'Literature',
  'Logistics',
  'Management',
  'Mandarin',
  'Marine Science',
  'Market Research',
  'Marketing',
  'Materials Science',
  'Mathematics',
  'Mechanical Engineering',
  'Media Management',
  'Media Studies',
  'Medical Imaging',
  'Medical Laboratory Science',
  'Medicine',
  'Mechatronics',
  'Middle Eastern Studies',
  'Midwifery',
  'Mineral and Mining Engineering',
  'Modern Languages',
  'Molecular Biology',
  'Music',
  'Mythology and Folklore',
  'Nanotechnology',
  'Natural Science',
  'Network Administration',
  'Neuroscience',
  'Nursing',
  'Obstetrics',
  'Occupational Health and Safety',
  'Occupational Therapy',
  'Oceanography',
  'Online Learning',
  'Operations Management',
  'Paediatrics',
  'Painting',
  'Paralegal Studies',
  'Peace and Conflict Studies',
  'Performing Arts',
  'Perioperative Medicine',
  'Pharmaceutical Sciences',
  'Pharmacy',
  'Philosophy',
  'Photography and Visual Media',
  'Physical Science',
  'Physical Therapy',
  'Physics',
  'Political Science',
  'Preventative Medicine',
  'Primary Health Care',
  'Project Management',
  'Psychological Sciences',
  'Psychology',
  'Public Administration',
  'Public Health',
  'Public Policy',
  'Public Relations',
  'Radiation Sciences',
  'Regional Planning',
  'Religious Studies',
  'Renewable Energy',
  'Research',
  'Risk and Compliance',
  'Risk Management',
  'Robotics',
  'Rural Health',
  'School Administration',
  'Science',
  'Sculpture',
  'Secondary Education',
  'Social Policy and Administration',
  'Social Sciences',
  'Social Work',
  'Sociology',
  'Software Development',
  'Soil Science',
  'Spanish',
  'Space Science',
  'Special Education',
  'Sports Medicine',
  'Statistics',
  'Strategic Marketing',
  'Structural Engineering',
  'Supply Chain Management',
  'Sustainable Development',
  'Taxation',
  'Teaching',
  'Technology',
  'Theatre',
  'Theology',
  'Tourism',
  'Transportation Planning',
  'Travel Management',
  'Urban Design',
  'Urban Planning',
  'Urban Studies',
  'Veterinary Science',
  'Visual Arts',
  'Wildlife Conservation',
  'Women’s Studies',
  'Systems Engineering',
]

export const degreeAndMajors = {
  '1st Year Bachelors': value,
  '2nd Year Bachelors': value,
  '3rd Year Bachelors': value,
  '4th Year Bachelors': value,
  '5th Year Bachelors': value,
  '6th Year Bachelors': value,
  '1st Year Masters': value,
  '2nd Year + Masters': value,
  '3rd Year + Masters': value,
  '1st Year PhD': value,
  '2nd Year PhD': value,
  '3rd Year PhD': value,
  '4th Year PhD': value,
  '5th Year PhD': value,
  '6th Year PhD': value,
  '6th Year + PhD': value,
}

const adminAndOther = [...value, 'Library', 'Commerce', 'Other']
export const occupationAndDepartment = {
  'Academic Advisor': adminAndOther,
  'Academic Writing Coach': adminAndOther,
  'Adjunct Lecturer': adminAndOther,
  'Admissions Officer': adminAndOther,
  'Alumni Relations Officer': adminAndOther,
  'Assistant Professor': adminAndOther,
  'Associate Professor': adminAndOther,
  'Athletics Coach': adminAndOther,
  Chancellor: adminAndOther,
  'Clinical Faculty': adminAndOther,
  'Compliance Officer': adminAndOther,
  'Content Writer': adminAndOther,
  'Custodial Staff': adminAndOther,
  'Data Analyst': adminAndOther,
  'Database Administrator': adminAndOther,
  'Dean of Faculty': adminAndOther,
  'Dean of Research': adminAndOther,
  'Dean of Students': adminAndOther,
  'Department Chair': adminAndOther,
  'Development Officer': adminAndOther,
  Director: adminAndOther,
  'Director of Admissions': adminAndOther,
  'Director of Diversity and Inclusion': adminAndOther,
  'Director of Finance': adminAndOther,
  'Director of Research and Development': adminAndOther,
  'Director of Student Affairs': adminAndOther,
  'Disability Support Specialist': adminAndOther,
  'E-learning Specialist': adminAndOther,
  'Emeritus Professor': adminAndOther,
  'Equal Opportunity Officer': adminAndOther,
  'Ethics Committee Member': adminAndOther,
  'Event Coordinator': adminAndOther,
  'Event Planner': adminAndOther,
  'Facilities Manager': adminAndOther,
  'Fieldwork Coordinator': adminAndOther,
  'Financial Aid Officer': adminAndOther,
  'Grant Writer': adminAndOther,
  'Graphic Designer': adminAndOther,
  Groundskeeper: adminAndOther,
  'Health Educator': adminAndOther,
  'Help Desk Technician': adminAndOther,
  'Human Resources Manager': adminAndOther,
  'Institutional Review Board (IRB) Coordinator': adminAndOther,
  Instructor: adminAndOther,
  'International Student Advisor': adminAndOther,
  'IT Administrator': adminAndOther,
  'IT Support Specialist': adminAndOther,
  'Lab Technician': adminAndOther,
  'Language Lab Coordinator': adminAndOther,
  Lecturer: adminAndOther,
  'Legal Counsel': adminAndOther,
  'Maintenance Technician': adminAndOther,
  'Marketing Specialist': adminAndOther,
  'Media Relations Specialist': adminAndOther,
  'Multimedia Technician': adminAndOther,
  'Music Conductor': adminAndOther,
  'Network Engineer': adminAndOther,
  Nurse: adminAndOther,
  'Office Manager': adminAndOther,
  'Physical Therapist': adminAndOther,
  'Policy Analyst': adminAndOther,
  'Postdoctoral Researcher': adminAndOther,
  Professor: adminAndOther,
  'Program Coordinator': adminAndOther,
  Provost: adminAndOther,
  'Public Relations Officer': adminAndOther,
  Registrar: adminAndOther,
  'Research Assistant': adminAndOther,
  'Research Faculty': adminAndOther,
  'Residence Life Coordinator': adminAndOther,
  'Scientific Equipment Specialist': adminAndOther,
  'Security Personnel': adminAndOther,
  'Senior Lecturer': adminAndOther,
  'Social Media Manager': adminAndOther,
  Statistician: adminAndOther,
  'Student Success Coach': adminAndOther,
  'Study Abroad Coordinator': adminAndOther,
  'System Analyst': adminAndOther,
  'Teaching Fellow': adminAndOther,
  'Technical Writer': adminAndOther,
  'Theatre Director': adminAndOther,
  'Transportation Coordinator': adminAndOther,
  Tutor: adminAndOther,
  'University Dean': adminAndOther,
  'University Physician': adminAndOther,
  'University President': adminAndOther,
  'Vice Chancellor': adminAndOther,
  'Visiting Faculty': adminAndOther,
  'Web Developer': adminAndOther,
  'Wellness Program Coordinator': adminAndOther,
  Admin: adminAndOther,
  Other: adminAndOther,
}

export const GenderOptions = ['Male', 'Female']

export const userType = ['student', 'faculty']
export const currYear = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th']
export enum userTypeEnum {
  Student = 'student',
  Faculty = 'faculty',
  Applicant = 'applicant',
}

export enum userCheckError {
  emailNotAvailable = 'Email is already taken',
  userNameNotAvailable = 'userName Already taken',
}

export const badgeData = [
  { name: 'Custom Emojis', bg: '#FDF4FF', color: '#C026D3' },
  { name: 'Unlimited AI Prompts', bg: '#ECFEFF', color: '#0891B2' },
  { name: 'Profile Badge', bg: '#F0FDF4', color: '#16A34A' },
  { name: 'Join Up 100 Groups', bg: '#F3F2FF', color: '#6744FF' },
  { name: '500 MB Upload', bg: '#FFFBEB', color: '#D97706' },
]
