export const COUNTRY: string[] = [
  'Japan',
  'Pakistan',
  'India',
  'China',
  'Korea, Republic of',
  'Tajikistan',
  'Kuwait',
  'Indonesia',
  'Maldives',
  'Malaysia',
  'Jordan',
  'Iran',
  'Armenia',
  'Philippines',
  'Taiwan, Province of China',
  'Thailand',
  'Russian Federation',
  'Viet Nam',
  'Kazakhstan',
  'Sri Lanka',
  'Macao',
  'Turkey',
  'Israel',
  'Mongolia',
  'Saudi Arabia',
  'Afghanistan',
  'Kyrgyzstan',
  'Nepal',
  'United Arab Emirates',
  'Lebanon',
  'Bangladesh',
  'Syrian Arab Republic',
  'Palestine, State of',
  'Iraq',
  'Azerbaijan',
  'Cambodia',
  'Singapore',
  'Yemen',
  'Brunei Darussalam',
  'Uzbekistan',
  'Bahrain',
  'Hong Kong',
  'Georgia',
  'Oman',
  'Vietnam',
  'Qatar',
  "Lao People's Democratic Republic",
  "Korea, Democratic People's Republic of",
  'Myanmar',
  'Bhutan',
  'Turkmenistan',
  'Belgium',
  'Portugal',
  'Slovakia',
  'France',
  'United Kingdom',
  'Ireland',
  'Germany',
  'Romania',
  'Ukraine',
  'Belarus',
  'Netherlands',
  'Czech Republic',
  'Poland',
  'Spain',
  'Norway',
  'Kosovo',
  'Iceland',
  'Austria',
  'Switzerland',
  'Latvia',
  'Italy',
  'Greece',
  'Bulgaria',
  'North Macedonia',
  'Hungary',
  'Finland',
  'Serbia',
  'Sweden',
  'Cyprus',
  'Bosnia and Herzegovina',
  'Albania',
  'Moldova, Republic of',
  'Lithuania',
  'Estonia',
  'Denmark',
  'Monaco',
  'Slovenia',
  'Liechtenstein',
  'Malta',
  'Croatia',
  'Andorra',
  'Montenegro',
  'Luxembourg',
  'San Marino',
  'Faroe Islands',
  'Holy See (Vatican City State)',
  'United States',
  'Canada',
  'Mexico',
  'Guatemala',
  'Belize',
  'Nicaragua',
  'Antigua and Barbuda',
  'Puerto Rico',
  'Dominican Republic',
  'El Salvador',
  'Costa Rica',
  'Dominica',
  'Cuba',
  'Haiti',
  'Saint Kitts and Nevis',
  'Bermuda',
  'Greenland',
  'Turks and Caicos Islands',
  'Montserrat',
  'Cayman Islands',
  'Honduras',
  'Panama',
  'Jamaica',
  'Saint Lucia',
  'Bahamas',
  'Saint Vincent and the Grenadines',
  'Guadeloupe',
  'Trinidad and Tobago',
  'Grenada',
  'Virgin Islands, British',
  'Bolivia, Plurinational State of',
  'Argentina',
  'Brazil',
  'Guyana',
  'Peru',
  'Venezuela, Bolivarian Republic of',
  'Ecuador',
  'Colombia',
  'Chile',
  'Uruguay',
  'Suriname',
  'Paraguay',
  'French Guiana',
  'Ghana',
  'Nigeria',
  'Uganda',
  'Kenya',
  'Senegal',
  'Tanzania, United Republic of',
  'Somalia',
  'Sudan',
  'Libya',
  'Cameroon',
  'Botswana',
  'Swaziland',
  'Zimbabwe',
  'Ethiopia',
  'Algeria',
  'Tunisia',
  'Morocco',
  'Egypt',
  'Zambia',
  'Angola',
  'Mozambique',
  'Rwanda',
  'Gambia',
  'Malawi',
  'Madagascar',
  'South Africa',
  'Lesotho',
  'Guinea',
  'Seychelles',
  "Côte d'Ivoire",
  'Namibia',
  'Equatorial Guinea',
  'Chad',
  'Togo',
  'Cape Verde',
  'Liberia',
  'Sierra Leone',
  'Central African Republic',
  'Mali',
  'Mauritius',
  'Burkina Faso',
  'Gabon',
  'Burundi',
  'Réunion',
  'Congo, the Democratic Republic of the',
  'Niger',
  'Mauritania',
  'Eritrea',
  'South Sudan',
  'Djibouti',
  'Benin',
  'New Zealand',
  'French Polynesia',
  'Papua New Guinea',
  'Niue',
  'Fiji',
  'Guam',
  'New Caledonia',
  'Samoa',
  'Australia',
].sort()
