name: Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-project: #First Job is to check the code formatting, linting and build the project.
    if: github.event.pull_request.draft == false
    name: Run Formatting Checks and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Code Formatting Check #Runs Prettier Script
        run: npm run prettier

      - name: Linting Check #Runs ESLint Script
        run: npm run lint

      - name: Test #Runs Jest Script
        run: npm run coverage

      - name: Upload coverage to Codecov #Uploads the coverage report to Codecov
        uses: codecov/codecov-action@v4-beta
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

      - name: Build #Build the project
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          GRAPHQL_REF: ${{ secrets.GRAPHQL_REF }}
        run: npm run build

      - name: Check Build Status
        run: |
          if [ $? -eq 0 ]; then
            echo "Build successful!🎉"
          else
            echo "Build failed!"
            exit 1
          fi

  chromatic-deployment: #Second Job is to deploy the project to Chromatic
    if: github.event.pull_request.draft == false
    name: Deploy Storybook to Chromatic
    runs-on: ubuntu-latest # Operating System
    # Job steps
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        run: npm install
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

